# fly.toml app configuration file generated for formbuilder-ui on 2025-07-22T15:09:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'formbuilder-ui'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    VITE_API_URL = { from_env = "VITE_API_URL" }
    VITE_JWT_STORAGE_KEY = { from_env = "VITE_JWT_STORAGE_KEY" }
    VITE_JWT_REFRESH_KEY = { from_env = "VITE_JWT_REFRESH_KEY" }
    VITE_API_TIMEOUT = { from_env = "VITE_API_TIMEOUT" }
    VITE_API_RETRY_ATTEMPTS = { from_env = "VITE_API_RETRY_ATTEMPTS" }

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
